source 'https://rubygems.org'

gem 'contentful-scheduler', '~> 0.1'
gem 'contentful-webhook-listener', '~> 0.2'
gem 'contentful-management', '~> 1.0'
gem 'resque', '~> 1.0'
gem 'resque-scheduler', '~> 4.0'
gem 'rake'
