require 'contentful/scheduler'

$stdout.sync = true

config = {
  redis: {
    host: 'localhost',
    port: 6379
  },
  spaces: {
    'YOUR_SPACE_ID' => {
      publish_field: 'publishDate'
    }
  },
  management_token: 'YOUR_TOKEN'
}

namespace :contentful do
  task :setup do
    Contentful::Scheduler.config = config
  end

  task :scheduler => :setup do
    Contentful::Scheduler.start
  end
end

require 'resque/tasks'
require 'resque/scheduler/tasks'

namespace :resque do
  task :setup => 'contentful:setup' do
    ENV['QUEUE'] = '*'
  end

  task :setup_schedule => :setup do
    require 'resque-scheduler'
  end

  task :scheduler => :setup_schedule
end
